version: “3.7”
services:
  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_PASS=1234567
      - RABBITMQ_DEFAULT_USER=admin
    ports:
      - 15672:15672
      - 5672:5672
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234567
    expose:
      - 27018
    command: --quiet

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234567
      - ME_CONFIG_MONGODB_SERVER=mongodb